In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import AffinityPropagation
from sklearn.datasets.samples_generator import make_blobs

In [4]:
# Make Dummy Data
centers = [[1, 1], [-1, -1], [1, -1]]
X, labels_true = make_blobs(n_samples=300, centers=centers, cluster_std=0.5, random_state=0)

In [5]:
X

array([[ 1.47504421,  0.9243214 ],
       [-0.02204385, -0.80495334],
       [-1.17671587, -1.80823709],
       [ 0.77223375,  1.00873958],
       [ 1.23283122,  0.23187816],
       [-0.92174673, -0.88390948],
       [ 1.65956844, -1.44120941],
       [ 0.33389417, -1.98431234],
       [-1.27143074, -0.79197498],
       [ 1.33614738,  1.20373092],
       [ 1.47123406, -1.13379737],
       [ 0.94839057,  1.20529925],
       [ 0.65271607,  0.92518273],
       [-0.11980203, -0.79925047],
       [ 1.26163833,  0.91422683],
       [ 0.87899009, -0.24086941],
       [ 0.74124048, -1.48941493],
       [ 0.71534397, -0.86504782],
       [ 0.80238551, -1.57971026],
       [ 0.51444771, -0.8425914 ],
       [ 1.38051886,  1.06083751],
       [ 0.42626567,  0.78108998],
       [ 0.74517391,  0.78096285],
       [ 0.78242322,  1.92463186],
       [ 0.76657723, -1.70845306],
       [ 0.82604393,  1.07817448],
       [ 1.1854125 , -0.9289691 ],
       [-1.15450648, -1.8380019 ],
       [ 1.4002824 ,

In [14]:
values_df = pd.read_csv("combined.csv", sep=",")

In [91]:
values_df.head(10)

frankfurt_aws  frankfurt_google  london_aws  london_google  mumbai_aws  \
0         1.0000            0.9096      0.6694         0.6053      0.3891   
1         0.8140            1.0000      0.5994         0.8098      0.2038   
2         0.6550            0.6205      1.0000         0.9988      0.3836   
3         0.5166            0.5426      0.9433         1.0000      0.2038   
4         0.3951            0.2198      0.3910         0.2220      1.0000   
5         0.0569            0.0772      0.0730         0.0912      0.9186   
6         0.4508            0.4358      0.4940         0.4666      0.2874   
7         0.3969            0.4063      0.4412         0.4282      0.2021   
8         0.3358            0.3579      0.3292         0.3694      0.2400   
9         0.3240            0.3524      0.3469         0.3545      0.2044   

   mumbai_google  northvirginia_aws  northvirginia_google  oregon_aws  \
0         0.0759             0.4606                0.4343      0.3303   
1         0.0676             0.4174                0.4246      0.3326   
2         0.0829             0.4674                0.4506      0.3667   
3         0.0892             0.4402                0.4460      0.3480   
4         0.9528             0.2954                0.2204      0.2412   
5         1.0000             0.1574                0.1868      0.2256   
6         0.1746             1.0000                0.9522      0.4580   
7         0.1863             0.8862                1.0000      0.4656   
8         0.2447             0.4587                0.4938      1.0000   
9         0.2579             0.4602                0.4562      0.5950   

   oregon_google  saopaulo_aws  saopaulo_google  singapore_aws  \
0         0.3475        0.2424           0.2441         0.3299   
1         0.3586        0.2268           0.2296         0.1416   
2         0.3683        0.2568           0.2670         0.3316   
3         0.3688        0.2428           0.2458         0.1587   
4         0.2221        0.1106           0.0588         0.4830   
5         0.2762        0.0154           0.0142         0.4843   
6         0.4878        0.3658           0.3714         0.2236   
7         0.5142        0.3400           0.3416         0.2480   
8         0.6598        0.3022           0.2944         0.3253   
9         1.0000        0.2858           0.2857         0.3359   

   singapore_google  sydney_aws  sydney_google  tokyo_aws  tokyo_google  
0            0.1388      0.1598         0.1646     0.2187        0.2127  
1            0.1572      0.1466         0.1733     0.2068        0.2424  
2            0.1690      0.1660         0.1862     0.2328        0.2530  
3            0.1730      0.1610         0.1927     0.2204        0.2418  
4            0.4674      0.2008         0.3230     0.3584        0.3698  
5            0.4852      0.3114         0.3688     0.3406        0.3650  
6            0.2648      0.2690         0.2847     0.3282        0.3429  
7            0.2738      0.2530         0.2964     0.3117        0.3726  
8            0.3332      0.3656         0.3213     0.4292        0.4185  
9            0.3526      0.3000         0.3462     0.3947        0.4046

In [35]:
values_df.describe()

frankfurt_aws  frankfurt_google  london_aws  london_google  mumbai_aws  \
count      18.000000         18.000000   18.000000      18.000000   18.000000   
mean        0.366511          0.361539    0.390639       0.393922    0.353517   
std         0.247538          0.259744    0.263654       0.281380    0.250729   
min         0.056900          0.077200    0.073000       0.091200    0.045500   
25%         0.205650          0.184250    0.232150       0.194550    0.203800   
50%         0.322200          0.250600    0.327550       0.273850    0.299500   
75%         0.437325          0.428425    0.480800       0.457000    0.387725   
max         1.000000          1.000000    1.000000       1.000000    1.000000   

       mumbai_google  northvirginia_aws  northvirginia_google  oregon_aws  \
count      18.000000          18.000000             18.000000   18.000000   
mean        0.309372           0.412628              0.424061    0.390039   
std         0.283479           0.214828              0.220018    0.175822   
min         0.028300           0.157400              0.186800    0.225600   
25%         0.084475           0.278900              0.276575    0.302850   
50%         0.251300           0.362100              0.388700    0.340300   
75%         0.370325           0.459825              0.449450    0.397000   
max         1.000000           1.000000              1.000000    1.000000   

       oregon_google  saopaulo_aws  saopaulo_google  singapore_aws  \
count      18.000000     18.000000        18.000000       18.00000   
mean        0.416928      0.267989         0.281022        0.37165   
std         0.176469      0.235757         0.263305        0.22828   
min         0.222100      0.015400         0.014200        0.09840   
25%         0.334450      0.112225         0.115850        0.22970   
50%         0.363450      0.234600         0.236850        0.33075   
75%         0.456900      0.298100         0.292225        0.47670   
max         1.000000      1.000000         1.000000        1.00000   

       singapore_google  sydney_aws  sydney_google  tokyo_aws  tokyo_google  
count         18.000000   18.000000      18.000000  18.000000     18.000000  
mean           0.377044    0.312406       0.368544   0.368717      0.392894  
std            0.252033    0.220272       0.248558   0.197144      0.206815  
min            0.106800    0.075000       0.130600   0.166200      0.186300  
25%            0.170000    0.162250       0.187825   0.223500      0.245050  
50%            0.342900    0.283900       0.322150   0.349500      0.369300  
75%            0.466600    0.364550       0.410125   0.414575      0.415025  
max            1.000000    1.000000       1.000000   1.000000      1.000000

In [17]:
values_df.drop(['Unnamed: 0','From'], axis=1, inplace= True)

In [60]:
X = values_df.values
X

array([[1.    , 0.9096, 0.6694, 0.6053, 0.3891, 0.0759, 0.4606, 0.4343,
        0.3303, 0.3475, 0.2424, 0.2441, 0.3299, 0.1388, 0.1598, 0.1646,
        0.2187, 0.2127],
       [0.814 , 1.    , 0.5994, 0.8098, 0.2038, 0.0676, 0.4174, 0.4246,
        0.3326, 0.3586, 0.2268, 0.2296, 0.1416, 0.1572, 0.1466, 0.1733,
        0.2068, 0.2424],
       [0.655 , 0.6205, 1.    , 0.9988, 0.3836, 0.0829, 0.4674, 0.4506,
        0.3667, 0.3683, 0.2568, 0.267 , 0.3316, 0.169 , 0.166 , 0.1862,
        0.2328, 0.253 ],
       [0.5166, 0.5426, 0.9433, 1.    , 0.2038, 0.0892, 0.4402, 0.446 ,
        0.348 , 0.3688, 0.2428, 0.2458, 0.1587, 0.173 , 0.161 , 0.1927,
        0.2204, 0.2418],
       [0.3951, 0.2198, 0.391 , 0.222 , 1.    , 0.9528, 0.2954, 0.2204,
        0.2412, 0.2221, 0.1106, 0.0588, 0.483 , 0.4674, 0.2008, 0.323 ,
        0.3584, 0.3698],
       [0.0569, 0.0772, 0.073 , 0.0912, 0.9186, 1.    , 0.1574, 0.1868,
        0.2256, 0.2762, 0.0154, 0.0142, 0.4843, 0.4852, 0.3114, 0.3688,
        0.3

In [81]:
X = (X+X.T)/2

In [83]:
X_symm

array([[1.     , 0.8618 , 0.6622 , 0.56095, 0.3921 , 0.0664 , 0.4557 ,
        0.4156 , 0.33305, 0.33575, 0.23115, 0.2383 , 0.32515, 0.1401 ,
        0.15985, 0.164  , 0.21135, 0.21165],
       [0.8618 , 1.     , 0.60995, 0.6762 , 0.2118 , 0.0724 , 0.4266 ,
        0.41545, 0.34525, 0.3555 , 0.2372 , 0.2416 , 0.1438 , 0.1501 ,
        0.1595 , 0.16195, 0.2209 , 0.2399 ],
       [0.6622 , 0.60995, 1.     , 0.97105, 0.3873 , 0.07795, 0.4807 ,
        0.4459 , 0.34795, 0.3576 , 0.2444 , 0.25805, 0.32875, 0.15215,
        0.166  , 0.1767 , 0.2327 , 0.2445 ],
       [0.56095, 0.6762 , 0.97105, 1.     , 0.2129 , 0.0902 , 0.4534 ,
        0.4371 , 0.3587 , 0.36165, 0.25125, 0.264  , 0.15895, 0.1727 ,
        0.1732 , 0.18155, 0.2352 , 0.25365],
       [0.3921 , 0.2118 , 0.3873 , 0.2129 , 1.     , 0.9357 , 0.2914 ,
        0.21125, 0.2406 , 0.21325, 0.1007 , 0.05215, 0.47735, 0.47455,
        0.1973 , 0.3173 , 0.3603 , 0.3715 ],
       [0.0664 , 0.0724 , 0.07795, 0.0902 , 0.9357 , 1.     , 0.1

In [84]:
af = AffinityPropagation(preference=-50, affinity='euclidean', damping = 0.5, verbose=True, max_iter=20000, convergence_iter=150).fit(X)
cluster_centers_indices = af.cluster_centers_indices_
labels = af.labels_

#n_clusters_ = len(cluster_centers_indices)

Converged after 181 iterations.


In [85]:
n_clusters_

1

In [86]:
print('Estimated number of clusters: %d' % n_clusters_)

Estimated number of clusters: 1


In [87]:
cluster_centers_indices

array([9])

In [88]:
print(af.cluster_centers_indices_)

[9]


In [80]:
af.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
af.cluster_centers_

array([[0.33575, 0.3555 , 0.3576 , 0.36165, 0.21325, 0.26705, 0.474  ,
        0.4852 , 0.6274 , 1.     , 0.29605, 0.30995, 0.33555, 0.3607 ,
        0.31295, 0.3418 , 0.41065, 0.4358 ]])